### ISSUE TITLE
Issue with `ibgp/2-transit` lab

### ISSUE THREAD

**Issue by bilalbox** [bgplab/bgplab#17]
Hello,

First, thanks for creating and sharing this amazing learning resource! I have been out of the networking space for almost a decade and in trying to build my chops back up I came across containerlab.dev, then netlab.tools, then finally this goldmine! This is the pinnacle of lab testing for learning and R&D, I am very excited to see where this goes.

As for my issue, I did run into a problem with the [transit network](ibgp/2-transit) lab, which may be due to my misunderstanding of the intent of the exercise, or a bug with the my setup:
* Platform: Codespaces (2-core/8G/32GB system)
* Netlab version: 1.8.4
* Images: Cumulus (networkop/cx:4.4.0)

Because BGP is not enabled on the `core` device, in order to setup the IBGP full-mesh I need to enable it. So following the method used effectively in all the previous labs, I did a `sudo echo "bgpd=yes" >> /etc/frr/daemons` followed by a `sudo systemctl restart frr` but found that upon reboot the OSPF and interface configurations were cleared from the running-configuration:
```
core(config)# do sh run
Building configuration...

Current configuration:
!
frr version 7.5+cl4.4.0u4
frr defaults datacenter
hostname core
log syslog informational
service integrated-vtysh-config
!
line vty
!
end
```

In attempting to add a new ospf configuration, I got a `The network command is not supported in multi-instance ospf` which tells me that the protocol was still configured somewhere:
```
core(config)# router ospf 1
core(config-router)# network 10.0.0.1/32 area 0
The network command is not supported in multi-instance ospf
```

Is there a different way for enabling BGP on the core router required for this lab? I could use the netlab `bgp` module in the `topology.yml` file but it seems like that would sort of miss the point of the exercise 😄

Is there any chance that there's an issue related to bouncing the FRR daemons when using the IP unnumbered configuration on the CORE interface?

**Comment by ipspace** [comment]
Thanks for pointing this out. Restarting FRR daemons loses configuration (for obvious reasons ;) which means you have to save it with the "write" command before restarting the daemons. Will add that to the "mastering FRR" lab (give me a day or so, the sea view from my "summer office" is too tempting :).

On the OSPF front, I'm using interface OSPF configuration because it's simpler to generate with a template; you only need to know what interfaces to run OSPF on, not the IP addresses. It's interesting that the "we're using OSPF interface config" bit of information does not get lost during the restart.

On a tangential note, I'll make sure all Cumulus and FRR netlab configuration templates have a "do write" at the end.

**Comment by ipspace** [comment]
Here's a fun trivia you might enjoy (or get confused by): if you configure `router ospf`, it works as expected, if you use `router ospf 1`, FRR assumes there will be `router ospf 2` (or whatever), pretends it's in _multi-instance_ mode even though there's only a single instance configured, and refuses the `network` command. 🤦‍♂️

Obviously, I'll fix the instructions, I just had to do a bit of testing first.
