### ISSUE TITLE
2-transit not working (clab/frr)

### ISSUE THREAD

**Issue by barajus** [bgplab/bgplab#8]
Hi back, I found a bit of time to play again, and hit this issue:

```
ubuntu@primary:~/bgplab/ibgp/2-transit$ netlab up
Errors encountered while processing topology.yml
IncorrectValue in interfaces: Device frr used on node core cannot run OSPF over unnumbered interface
IncorrectValue in interfaces: Device frr used on node pe2 cannot run OSPF over unnumbered interface
Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

defaults.yml
```
device: frr            # Change to your preferred network device
provider: clab          # Change to virtualbox or libvirt if needed
```

**Comment by ipspace** [comment]
Thanks a million for reporting this. I use Cumulus Linux containers instead of FRR, so I didn't catch it.

I could try to implement unnumbered interfaces on FRR (would ship in 1.8), change the lab to not use unnumbereds (but I wanted to have clean routing tables to make it easier), or have a separate topology (or a plugin that fixes the topology) for FRR.

Which one do you think makes most sense?

**Comment by barajus** [comment]
I think the first option (unnumbered) is the easiest and cleanest option right?
thanks!

Julien

**Comment by ipspace** [comment]
OK, will try to make unnumbered interfaces working on FRR.

FWIW, the lab instructions include a warning saying "if your devices does not support unnumbered interfaces, remove `ipv4: True` from lab topology" ;)

Anyhow, as this might happen to people using other devices, I'll add a plugin that will remove the unnumbered prefix in case one of the devices connected to that link does not support it.

**Comment by ipspace** [comment]
Fortunately I checked before starting to fix this stuff, and it turns out OSPF over unnumbered IPv4 worked on FRR "forever", we just didn't mark it as available. The "it really works" fix comes in 1.8.0, in the meantime, add the following line to defaults.yml:

```
devices.frr.features.ospf.unnumbered: true
```

It if works for you as well (I tested it with 1.6.4, the lab came up, and the OSPF session started) I'll add that line to the default.yml file in the repository.

**Comment by barajus** [comment]
I confirm it works as well with the line in defaults.yml 👍

**Comment by ipspace** [comment]
Decided to add the 'fix the subnet' plugin after all, hopefully making life a bit easier for users using less-capable devices (example: IOSv).

Thanks again for reporting this one, please keep them coming ;)
